# Generated by Django 3.1 on 2023-09-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0003_auto_20230909_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
                ('file', models.FileField(blank=True, null=True, upload_to='src/media/')),
                ('file_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='friend',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='friend',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='share',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='share',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
