# Generated by Django 3.1 on 2023-09-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0007_auto_20230911_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_reacts',
            field=models.IntegerField(default=0),
        ),
    ]
