# Generated by Django 3.1 on 2023-09-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0008_post_count_reacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='react_type',
            field=models.CharField(default='NOT_REACT', max_length=20),
        ),
    ]
