# Generated by Django 3.1 on 2023-09-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0011_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='web_api.comment'),
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
