# Generated by Django 3.1 on 2023-09-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0012_auto_20230917_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
