# Generated by Django 3.1 on 2023-09-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0013_post_parent_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='is_followed',
            field=models.BooleanField(default=True),
        ),
    ]
